plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.147'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

allprojects {
    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}

evaluationDependsOn(':Core')
evaluationDependsOn(':Settlements')

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'guest_core,guest_settlements'
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'guest_core,guest_settlements'
        }

        configureEach {
            gameDirectory = rootProject.file('run')

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        guest_core {
            sourceSet project(':Core').sourceSets.main
        }
        guest_settlements {
            sourceSet project(':Settlements').sourceSets.main
        }
    }
}