package com.vortexso.guest_wilds;

public record WildsParameters(
    double wearHalfLifeDays,
    double trampleWear,
    double wornWear,
    double pathWear,
    double revertFraction,
    double routeMeanderBlocks,
    double routeMeanderWavelength,
    double roadVergeShare,
    double residentsPerChunk,
    double lairCapacity,
    double zombieGrowthPerDay,
    double spiderGrowthPerDay,
    double creeperGrowthPerDay,
    double skeletonGrowthPerDay,
    double lairMortalityPerDay,
    double competition,
    double winterCompetition,
    long lairInhabitedLimit,
    double jockeyStableDays,
    double boggedResidenceDays,
    double babyZombieShare,
    double caveSpiderAgeDays,
    int caveSpiderDepth,
    double caveSpiderShare,
    int materializeRadius,
    int materializePerCheck,
    int roamRadius,
    int emigrantRange,
    int renewDays,
    float clutchPowerPerEgg,
    double herdBirthPerDay,
    double herdMortalityPerDay,
    double predationPerDayAtBaseline,
    double grazePerAnimalDay,
    double vegetationRegrowthPerDay,
    double migrateBelowVegetation,
    double predatorAvoidance,
    double herdCapacity,
    int herdGatherRadius,
    int herdBatch,
    int herdFollowRadius,
    double trailWearPerAnimal,
    double wolvesPerPredatorUnit,
    double packCapacity,
    double oceanShoal,
    double riverShoal,
    double lakeShoal,
    double shoalRegrowthPerDay,
    double multiCatchRatio,
    double depletedRatio,
    int waitTicksPerExtraFish,
    double mixedArtifactChance,
    double visibleFishRatio,
    int maxVisibleFish,
    int schoolMin,
    int schoolMax,
    double bushDays,
    double saplingDays) {

  public static final WildsParameters DEFAULT =
      new WildsParameters(
          4.0, 8.0, 32.0, 96.0, 0.5, 2.0, 20.0, 0.25, 0.17, 8.0, 0.35, 0.5, 0.25, 0.15, 0.03, 0.7,
          1.5, 24_000L, 16.0, 32.0, 0.25, 32.0, 10, 0.5, 48, 3, 32, 96, 8, 0.75F, 0.05, 0.01, 0.005,
          0.02, 0.05, 0.3, 0.3, 20.0, 160, 16, 7, 2.0, 6.0, 8.0, 40.0, 24.0, 12.0, 0.3, 0.6, 0.15,
          1200, 0.25, 0.5, 40, 10, 20, 3.0, 10.0);
}
