apply plugin: 'java-library'

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-common"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net'
        content { includeGroupAndSubgroups('net.fabricmc') }
    }
    maven {
        name = 'Fuzs'
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
        content { includeGroupAndSubgroups('fuzs') }
    }
    mavenCentral()
}

neoForge {
    neoFormVersion = neo_form_version
}

dependencies {
    compileOnly "net.fabricmc:sponge-mixin:${mixin_version}"
    compileOnly "io.github.llamalad7:mixinextras-common:${mixinextras_version}"
    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${config_port_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
