license="${mod_license}"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Vortex_So"

description='''
Living ancient cities: silent Architects who tend the sculk ritual, calm the Warden with a melody and slowly decline, plus the infected variants of their descendants.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.guest_architects]]
    modId = "guest_core"
    type = "required"
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"